### PR TITLE
Quick fix for error handling

### PR DESCRIPTION
**Pull request by Capt-Brunch**
Takes out 'raise' to more gracefully handles error conditions. 

Note, raises warning on games with Unicode characters due to my error handling, but doesn't break anything.

### CODE REVIEW

**Comment by thouis** [comment]
There are a lot of games that use Unicode, so I'd rather not merge this.  Any ideas how to address that?

**Comment by Capt-Brunch** [comment]
I have a few ideas that should be super easy to implement. I can poke at it
in a few hours and send a new pull request with that fixed.

-Jared

**Comment by Capt-Brunch** [comment]
Alright, fixed that with cleaner code anyway.

**Comment by thouis** [comment]
Thanks, merged!

**Pull request merged**
